"""add expected_candidate_count to exam_centres

Revision ID: 07b561968719
Revises: 6e0d8f2604d1
Create Date: 2026-08-29 23:37:02.757460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07b561968719'
down_revision: Union[str, Sequence[str], None] = '6e0d8f2604d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('exam_centres', sa.Column('expected_candidate_count', sa.Integer(), nullable=False, server_default='100'))
    # server_default only affects future inserts unless removed — drop it
    # after backfilling so the column's real default going forward is
    # controlled by the Python model (default=100), not a DB-side default.
    op.alter_column('exam_centres', 'expected_candidate_count', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_centres', 'expected_candidate_count')
    # ### end Alembic commands ###
