"""create exam_events, paper_variants, variant_assignments

Revision ID: 090db3f13c01
Revises: 0bc027541b50
Create Date: 2026-08-27 15:17:09.687183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '090db3f13c01'
down_revision: Union[str, Sequence[str], None] = '0bc027541b50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exam_name', sa.String(), nullable=False),
    sa.Column('exam_start_epoch', sa.Float(), nullable=False),
    sa.Column('override_window_end_epoch', sa.Float(), nullable=False),
    sa.Column('num_variants', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('total_custodians', sa.Integer(), nullable=False),
    sa.Column('override_threshold', sa.Integer(), nullable=False),
    sa.Column('assignment_secret_hash', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'COMPILED', 'LIVE', 'CLOSED', name='exameventstatus'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exam_event_id', sa.UUID(), nullable=False),
    sa.Column('variant_index', sa.Integer(), nullable=False),
    sa.Column('ciphertext', sa.Text(), nullable=False),
    sa.Column('nonce', sa.String(), nullable=False),
    sa.Column('question_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.ForeignKeyConstraint(['exam_event_id'], ['exam_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variant_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exam_event_id', sa.UUID(), nullable=False),
    sa.Column('centre_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('assignment_hash', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['centre_id'], ['exam_centres.id'], ),
    sa.ForeignKeyConstraint(['exam_event_id'], ['exam_events.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['paper_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variant_assignments')
    op.drop_table('paper_variants')
    op.drop_table('exam_events')
    # ### end Alembic commands ###
