"""create exam_centres and questions tables

Revision ID: 0bc027541b50
Revises: bb85493c9831
Create Date: 2026-08-27 15:09:23.150194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bc027541b50'
down_revision: Union[str, Sequence[str], None] = 'bb85493c9831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_centres',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('centre_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('acceptable_radius_m', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_centres_centre_code'), 'exam_centres', ['centre_code'], unique=True)
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contributor_id', sa.UUID(), nullable=False),
    sa.Column('encrypted_content', sa.Text(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contributor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_index(op.f('ix_exam_centres_centre_code'), table_name='exam_centres')
    op.drop_table('exam_centres')
    # ### end Alembic commands ###
