"""create custodians and share_submissions with unique share_x constraint

Revision ID: 337e517615dd
Revises: 090db3f13c01
Create Date: 2026-08-27 15:27:40.908230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '337e517615dd'
down_revision: Union[str, Sequence[str], None] = '090db3f13c01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custodians',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exam_event_id', sa.UUID(), nullable=False),
    sa.Column('custodian_type', sa.Enum('EXAM_BOARD_REP', 'INDEPENDENT_REGULATOR', 'MAGISTRATE_OBSERVER', 'STATE_EDU_OFFICER', 'JUDICIARY_AUDITOR', name='custodiantype'), nullable=False),
    sa.Column('share_x', sa.Integer(), nullable=False),
    sa.Column('share_y_encrypted', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['exam_event_id'], ['exam_events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_event_id', 'share_x', name='uq_custodian_event_sharex')
    )
    op.create_table('share_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('custodian_id', sa.UUID(), nullable=False),
    sa.Column('submission_type', sa.Enum('STANDARD', 'OVERRIDE', name='submissiontype'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ntp_verified_time', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['custodian_id'], ['custodians.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['paper_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('share_submissions')
    op.drop_table('custodians')
    # ### end Alembic commands ###
