"""create access_attempts and print_jobs

Revision ID: 5698dde167fe
Revises: 337e517615dd
Create Date: 2026-08-27 15:31:35.383646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5698dde167fe'
down_revision: Union[str, Sequence[str], None] = '337e517615dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('role_check_passed', sa.Boolean(), nullable=False),
    sa.Column('device_check_passed', sa.Boolean(), nullable=False),
    sa.Column('location_check_passed', sa.Boolean(), nullable=False),
    sa.Column('time_window_check_passed', sa.Boolean(), nullable=False),
    sa.Column('overall_passed', sa.Boolean(), nullable=False),
    sa.Column('declared_latitude', sa.Float(), nullable=True),
    sa.Column('declared_longitude', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('print_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('centre_id', sa.UUID(), nullable=False),
    sa.Column('simulated_printer_id', sa.Integer(), nullable=False),
    sa.Column('copies_assigned', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['centre_id'], ['exam_centres.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['paper_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('print_jobs')
    op.drop_table('access_attempts')
    # ### end Alembic commands ###
