"""add custodian_variant_shares table

Revision ID: 63153bc7686f
Revises: 557f13c4d14f
Create Date: 2026-09-07 22:17:06.766368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63153bc7686f'
down_revision: Union[str, Sequence[str], None] = '557f13c4d14f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custodian_variant_shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custodian_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('share_y_encrypted', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['custodian_id'], ['custodians.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['paper_variants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custodian_id', 'variant_id', name='uq_custodian_variant')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custodian_variant_shares')
    # ### end Alembic commands ###
