"""add custodian_variant_shares table

Revision ID: 7435bcd36c66
Revises: d37aaf7c7d0b
Create Date: 2026-09-07 11:17:35.974357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7435bcd36c66'
down_revision: Union[str, Sequence[str], None] = 'd37aaf7c7d0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
