"""add unique constraint on devices user_id fingerprint

Revision ID: 9e1d93fe9085
Revises: 63153bc7686f
Create Date: 2026-09-09 11:57:20.211705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e1d93fe9085'
down_revision: Union[str, Sequence[str], None] = '63153bc7686f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_device_user_fingerprint', 'devices', ['user_id', 'fingerprint'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_device_user_fingerprint', 'devices', type_='unique')
    # ### end Alembic commands ###
