"""create ledger_entries

Revision ID: b12779248c69
Revises: 5698dde167fe
Create Date: 2026-08-27 15:35:28.039682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b12779248c69'
down_revision: Union[str, Sequence[str], None] = '5698dde167fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('QUESTION_SUBMITTED', 'VARIANTS_COMPILED', 'SHARE_SUBMITTED', 'UNLOCK_DENIED_THRESHOLD', 'UNLOCK_DENIED_TIME', 'VARIANT_DECRYPTED', 'PRINT_JOB_COMPLETED', 'ACCESS_DENIED', 'OVERRIDE_REQUESTED', 'OVERRIDE_APPROVED', name='ledgereventtype'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('exam_event_id', sa.UUID(), nullable=True),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('prev_hash', sa.String(), nullable=False),
    sa.Column('entry_hash', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['exam_event_id'], ['exam_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ledger_entries')
    # ### end Alembic commands ###
