"""split custodian identity from per-variant shares (Module 1 auto-assembly)

Revision ID: d258685ffaaa
Revises: 7435bcd36c66
Create Date: 2026-09-07 11:25:54.013812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd258685ffaaa'
down_revision: Union[str, Sequence[str], None] = '7435bcd36c66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
