"""split custodian identity from per-variant shares (Module 1 auto-assembly)

Revision ID: d37aaf7c7d0b
Revises: 0275cb55636c
Create Date: 2026-09-06 15:21:19.090352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd37aaf7c7d0b'
down_revision: Union[str, Sequence[str], None] = '0275cb55636c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custodians', 'share_y_encrypted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custodians', sa.Column('share_y_encrypted', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
